### ISSUE TITLE
Show notes on dots

### ISSUE THREAD

**Issue by afranke** [bragefuglseth/fretboard#17]
Showing notes on the dots would not only help with learning, but also make it clearer that one is where they think they are on the fretboard.

**Comment by EuriNaiz** [comment]
I think that showing numbers instead notes will be better, because with fingering exercises and maping you'll learn where are the notes in your instrument. In exchange the numbers are more useful to teach how are the chords well done to avoid lesions in your hands.

Here is an example what I mean, Ukelib.com  and Gtrlib.com do that:

![image](https://github.com/bragefuglseth/fretboard/assets/69781814/78aab16b-d032-401e-aa77-c0265d1a26be)

**Comment by EuriNaiz** [comment]
why don't delegate that work to the users? in that way the work can be automatised and minor for each collaborator.

The only work could be adding those functions and the network additional permission in the flatpak package (for sending that data).

**Comment by bragefuglseth** [comment]
To get back on topic: I see how displaying note names inside of the dots can be useful for learning and orienting oneself on the diagram. I'm concerned about information overload, though. The chord diagram already has a lot of visual information for people to process, and adding note names to the mix might add more clutter than it's worth. The diagram already shows where on the neck a chord is played, and from what I can find online, most other chord diagrams limit themselves to this as well. Showing fingerings has the same set of drawbacks.

**Comment by bragefuglseth** [comment]
An alternative could be to display the note names as tooltips. This would help with a11y too.

**Comment by bragefuglseth** [comment]
I decided to implement this with tooltips, because:
- It lets people see specific note names if needed
- It doesn't clutter the interface
- It works really well with screen readers, and thus lets us progress on #11 as well.
