### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by arielbonfim** [bragefuglseth/fretboard#30]
The fret balls are not showing up

Just open up the software and try to see a chord

**Expected behavior**
The chord must have indication to where to press on guitar arm

**Screenshots**
![image](https://github.com/bragefuglseth/fretboard/assets/104951987/55190332-0339-446b-810b-c5076d963679)

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version 21.1

**Comment by bragefuglseth** [comment]
Hi, and thanks for your bug report! It seems like you're using a custom theme. Have you tried to unset it? Was it applied by yourself or did it come built into Mint?

**Comment by bragefuglseth** [comment]
Also, may I ask if you got the app from Flathub or from Mint's repositories?

**Comment by arielbonfim** [comment]
Hi! Thanks for answer! I got the app via Flathub, the custom theme come built into Mint. The problem remained when I changed the system theme.

**Comment by bragefuglseth** [comment]
I'm not sure how up-to-date you are on the [theming situation](https://blogs.gnome.org/tbernard/2018/10/15/restyling-apps-at-scale/), but the way GTK apps are "themed" is actually based on a misuse of GTK's styling system. It has just been done for so long now that many people think GTK actually has theming support, and desktop environments like Cinnamon (which Mint uses) even has support for this misuse built in.

The problem with theming being based on a hack is that it can break apps, which this is a good example of. I've built Fretboard with Adwaita, which means that the app expects to always be used with the Adwaita stylesheet (what's often referred to as a "theme"). The Adwaita stylesheet has a special color defined in it that I use for the chord diagram dots. This color automatically adapts to light/dark mode, since the blue needs to be tinted slightly differently in the two modes, and in the future, it might also adapt to your chosen accent color. Mint's theme doesn't define this color, so the dots just become transparent. If it works in the main view, that's because the dots there are buttons, which Mint's stylesheet might actually support because they're, well, buttons.

The other problem here is that the Adwaita library normally tells the app if it's in light or dark mode. Just changing the underlying stylesheet, like Mint does, won't make the app realize this, so the fretboard backdrop and the icons are colored like the app was in light mode, which makes for some jarring contrast issues.

We've tried to [tell distros](https://stopthemingmy.app/) about this issue to make them stop theming apps that weren't made for their specific stylesheets, but unfortunately we've faced a lot of pushback for this, and many distros are still forcing custom stylesheets on apps that weren't made for them.

If you applied the theme yourself, you've just encountered one of the drawbacks of theming. It's of course fine to tinker with your system, just remember to report any future visual issues with GTK apps to the theme developers and not the app developers. If this is something Mint has done automatically, please contact the Mint team and tell them that they are breaking apps by default.

For now, I'll artificially block the misuse of the styling system in Fretboard. I usually don't resort to technical prohibitions like this, but any other stylesheet than Adwaita breaks the app, so I have to if I don't want it to break.
