### ISSUE TITLE
[Feature] Use and accept ♯ and ♭

### ISSUE THREAD

**Issue by wjt** [bragefuglseth/fretboard#36]
**Describe the bug**

Only the symbols `#` and `b` are accepted as input, or displayed, in the chord entry, not `♯` nor `♭`.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click the ‘Chord Name’ entry
2. Type `B♭`

**Expected behaviour**

The chord `x13331` is displayed.

**Screenshots**

![Screenshot from 2023-10-13 20-56-36](https://github.com/bragefuglseth/fretboard/assets/86760/c806d0be-9faf-4661-8df4-0bb22f7efae2)

**Additional context**

You can type ♭ with `Compose` `#` `b` and ♯ with `Compose` `#` `#`. No rational human would do this rather than just `b` or `#`, you might think, but it was one of the first things I tried.

Aesthetically I think `B♭` and `A♯` look nicer than `Bb` and `A#`.

If it were me, I would:

1. Accept these characters as input
2. Normalise any entered chord to use the correct symbol
3. For extra credit, accept `𝄪` or `##` for double-sharp and `𝄫` or `bb` for double-flat.

**Comment by bragefuglseth** [comment]
Thanks for your suggestion! I made this into a feature request since the current behavior is expected, and consequently not a bug, but I agree that it would be cool to use the proper symbols here. For the sake of simplicity I think the internal representation should still be b and #, but in the entry and elsewhere it would definitely be cool to show them as / accept the unicode symbols.

**Comment by bragefuglseth** [comment]
The app now uses the unicode symbols everywhere :)

https://github.com/bragefuglseth/fretboard/assets/91388039/b7ec79de-7aa6-4fd8-a3bc-d2add8056669
